name: "CI"
on:
  pull_request:

jobs:
  check-merge-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check if there are merge commits
        run: |
          commits="$(git rev-list --merges origin/main..${{github.event.pull_request.head.sha}})"
          if [ -n "$commits" ]; then
            echo ""
            echo "==========="
            echo ""
            echo "Esse PR cont√©m commits de merge. Remova-os para poder mergear:"
            echo "$commits"
            exit 1
          fi
